@baseUrl = http://localhost:6400

#Health API
GET {{baseUrl}}/api/v1/health

### Get Data
GET {{baseUrl}}/api/v1/todos

### Get By ID
GET {{baseUrl}}/api/v1/todos/2

### Post Data
POST {{baseUrl}}/api/v1/todos
Content-Type: application/json

{
    "id":2,
    "title":"Cook your meals",
    "description":"Make chicken fried rice",
    "completed":false
}

### Update Data
PUT {{baseUrl}}/api/v1/todos/4
Content-Type: application/json

{
    "title":"Make sure erutto warmup first"
}

### Delete Data
DELETE {{baseUrl}}/api/v1/todos/1

