@baseUrl = http://localhost:6400


### Get Data
GET {{baseUrl}}/api/v1/todos

### Get By ID
GET {{baseUrl}}/api/v1/todos/2

### Post Data
POST {{baseUrl}}/api/v1/todos
Content-Type: application/json

{
    "id":3,
    "title":"testing",
    "description":"Testing done"
}

### Update Data
PUT {{baseUrl}}/api/v1/todos/3
Content-Type: application/json

{
    "title":"Make sure erutto warmup first"
}

### Delete Data
DELETE {{baseUrl}}/api/v1/todos/1

